# Generated by Django 5.1.5 on 2025-02-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('profesor', models.CharField(blank=True, max_length=100, null=True)),
                ('notas_adicionales', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
