# Generated by Django 5.1.5 on 2025-02-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudiantes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="nombre",
            field=models.CharField(default="Anonimo", max_length=100),
        ),
    ]
